#!/bin/sh

echo "## Deleting out/"
rm -rf out
mkdir -p out

echo

possible=3
ran=0

compile () {
    echo -n "# ($1) $3 with options $2 ... "
    bin/cljsc test "$2" > "$3"
    echo "done"
}

echo "## Compiling clojurescript"

echo "# (scr) Script compilation with {:optimizations :none} deactivated until fixed"
#FIXME compile "scr" "{:optimizations :none}" out/core-test.js
compile "whi" "{:optimizations :whitespace :pretty-print true}" out/core-whitespace-test.js
compile "adv" "{:optimizations :advanced :debug true :pretty-print true}" out/core-advanced-test.js

echo

run_file () {
    echo "# ($1) `eval "$2 $3 2>&1"`"
}

run_tests () {
    HOME=`eval "echo $1"`
    if [ -z "$HOME" ]; then
	echo "##! $1 not set, skipping $2 tests"
    else
	CMD="${HOME}/$3"
	echo "## Testing with $2"
	#FIXME run_file "scr" "$CMD" out/core-test.js
	run_file "whi" "$CMD" out/core-whitespace-test.js
	run_file "adv" "$CMD" out/core-advanced-test.js
	ran=$[ran+1]
    fi
    echo
}

run_tests '$SPIDERMONKEY_HOME' "SpiderMonkey" "js -m -f"
run_tests '$JSC_HOME' "JavaScriptCore" "jsc -f"
run_tests '$V8_HOME'  "V8"             "d8"

echo
echo "Tested with $ran out of $possible possible js targets"
